version: "3.9" 

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app                  # Sync app source code
      - ./app/uploads:/code/app/uploads # Sync uploaded images
      - ./data:/code/data               # Optional: if you store recipes_dt.json here
    environment:
      - ENV=development