version: "3.9" 

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - ENV=development